name = "cyrix-modern-app"
pages_build_output_dir = "dist"


[[d1_databases]]
binding = "DB"
database_name = "cyrixapp"
database_id = "9dd13367-e6a6-43de-a1c1-613d40c33ced"

[[r2_buckets]]
binding = "BILLS_BUCKET"
bucket_name = "cyrixapp"
